export const DOCTOR_LIST_REQUEST='DOCTOR_LIST_REQUEST';
export const DOCTOR_LIST_SUCCESS='DOCTOR_LIST_SUCCESS';
export const DOCTOR_LIST_FAIL='DOCTOR_LIST_FAIL';

export const DOCTOR_REQUEST='DOCTOR_REQUEST';
export const DOCTOR_SUCCESS='DOCTOR_SUCCESS';
export const DOCTOR_FAIL='DOCTOR_FAIL';

export const DOCTOR_PROFILE_UPDATE_REQUEST="DOCTOR_PROFILE_UPDATE_REQUEST";
export const DOCTOR_PROFILE_UPDATE_SUCCESS="DOCTOR_PROFILE_UPDATE_SUCCESS";
export const DOCTOR_PROFILE_UPDATE_FAILED="DOCTOR_PROFILE_UPDATE_FAILED";

export const DOCTOR_CREATE_REQUEST='DOCTOR_CREATE_REQUEST';
export const DOCTOR_CREATE_SUCCESS='DOCTOR_CREATE_SUCCESS';
export const DOCTOR_CREATE_FAIL='DOCTOR_CREATE_FAIL';

export const DOCTOR_DELETE_REQUEST='DOCTOR_DELETE_REQUEST';
export const DOCTOR_DELETE_SUCCESS='DOCTOR_DELETE_SUCCESS';
export const DOCTOR_DELETE_FAIL='DOCTOR_DELETE_FAIL';



