export const PATIENT_LIST_REQUEST='PATIENT_LIST_REQUEST';
export const PATIENT_LIST_SUCCESS='PATIENT_LIST_SUCCESS';
export const PATIENT_LIST_FAIL='PATIENT_LIST_FAIL';

export const PATIENT_REQUEST='PATIENT_REQUEST';
export const PATIENT_SUCCESS='PATIENT_SUCCESS';
export const PATIENT_FAIL='PATIENT_FAIL';

export const PATIENT_PROFILE_UPDATE_REQUEST="PATIENT_PROFILE_UPDATE_REQUEST";
export const PATIENT_PROFILE_UPDATE_SUCCESS="PATIENT_PROFILE_UPDATE_SUCCESS";
export const PATIENT_PROFILE_UPDATE_FAILED="PATIENT_PROFILE_UPDATE_FAILED";

export const PATIENT_CREATE_REQUEST='PATIENT_CREATE_REQUEST';
export const PATIENT_CREATE_SUCCESS='PATIENT_CREATE_SUCCESS';
export const PATIENT_CREATE_FAIL='PATIENT_CREATE_FAIL';

export const PATIENT_DELETE_REQUEST='PATIENT_DELETE_REQUEST';
export const PATIENT_DELETE_SUCCESS='PATIENT_DELETE_SUCCESS';
export const PATIENT_DELETE_FAIL='PATIENT_DELETE_FAIL';



